// ==========================================
// WHY IT IS INCLUDED:
// Tests basic node matching.
//
// EXPECTED BEHAVIOR:
// Returns nodes based on labels.
// ==========================================

MATCH (o:Orders) RETURN o;
